name: 🏁 Windows Builds

on:
  workflow_call:

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GODOT_REF: 35cfaafda8073f700c9d2fe42a43d3d81eaaea67
  SCONSFLAGS: platform=windows verbose=yes warnings=all werror=yes debug_symbols=no module_text_server_fb_enabled=yes
  SCONS_CACHE_MSVC_CONFIG: true
  BASE_BRANCH: main

jobs:
  windows-editor:
    # Windows 10 with latest image
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor, tests=yes)
            cache-name: windows-editor
            target: editor
            tests: true
            # Skip debug symbols, they're way too big with MSVC.
            sconsflags: debug_symbols=no vsproj=yes
            bin: "./bin/godot.windows.editor.x86_64.exe"

          - name: Template (target=template_release)
            cache-name: windows-template
            target: template_release
            tests: false
            sconsflags: debug_symbols=no
    steps:
    - name: Clone godex
      uses: actions/checkout@v2
      with:
       path: modules/godex

    - name: Clone godot for godex
      uses: actions/checkout@v2
      with:
       repository: godotengine/godot
       ref: ${{ env.GODOT_REF }}
       path: godot

    - name: Apply patches
      run: |
        cd godot
        git apply ../modules/godex/patches/add_custom_iterator.patch --reject --ignore-space-change --ignore-whitespace
        git apply ../modules/godex/patches/Adjust_build_for_godex.patch --reject --ignore-space-change --ignore-whitespace

    - name: Setup Godot build cache
      uses: ./godot/.github/actions/godot-cache
      with:
        cache-name: ${{ matrix.cache-name }}
      continue-on-error: true

    - name: Setup python and scons
      uses: ./godot/.github/actions/godot-deps

    - name: Setup MSVC problem matcher
      uses: ammaraskar/msvc-problem-matcher@master

    - name: Compilation
      uses: ./godot/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
        platform: windows
        target: ${{ matrix.target }}
        tests: ${{ matrix.tests }}
        working-directory: godot

#      # Execute unit tests for the editor
#    - name: Unit tests
#      working-directory: godot
#      if: ${{ matrix.tests }}
#      run: |
#        ${{ matrix.bin }} --version
#        ${{ matrix.bin }} --help
#        ${{ matrix.bin }} --test
#
#    - name: Prepare artifact
#      working-directory: godot
#      run: |
#        Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
#
#    - name: Upload artifact
#      uses: ./godot/.github/actions/upload-artifact
#      with:
#        name: ${{ matrix.cache-name }}
